name: Check websites for changes

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to run this job on'
        required: true
        type: string
      csv-path:
        description: 'Path to a CSV containing the URLs'
        required: true
        type: string
      keywords-path:
        description: 'Path to a TXT containing the keywords'
        required: true
        type: string
      send-notifications:
        description: 'Run this workflow with notifications'
        default: true
        required: false
        type: boolean
      commit-error-count:
        description: 'Commit error count'
        default: true
        required: false
        type: boolean
      title:
        description: Title of this group of websites
        required: false
        default: ''
        type: string
    secrets:
      MS_TEAMS_WEBHOOK_URL:
        required: true
jobs:
  build-matrix:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install certifi --upgrade
          sudo apt-get install sqlite3

      - id: set-matrix
        env:
           CSV_PATH: ${{ inputs.csv-path }}
        run: |
          matrix=$(./workflow/matrix.sh $CSV_PATH | jq -c '.')
          echo $matrix
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  crawl:
    needs: build-matrix
    runs-on: ubuntu-latest
    timeout-minutes: 180
    environment: ${{ inputs.environment }}
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix: ${{fromJSON(needs.build-matrix.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

          sudo apt update || true # do not fail if update does not work
          sudo apt-get install sqlite3
          sudo apt-get install poppler-utils
          if [ "${{ matrix.type }}" = "dynamic" ] ; then
                sudo apt-get install chromium-browser
          fi
      
      - name: Check website
        id: website
        run: |
          echo "URL: ${{ matrix.url }}, timeout: ${{ matrix.timeout }}"
          mkdir matches
          mkdir new_hashes
          python ./lib/website_matcher.py -u "${{ matrix.url }}" -l "${{ matrix.label }}" -g "${{ inputs.title }}" -f "hashes/${{ matrix.slug }}.txt" -k "${{ inputs.keywords-path }}" -n "new_hashes/${{ matrix.slug }}.txt" -w "${{ matrix.timeout }}" -t "${{ matrix.type }}" -o matches/${{ matrix.slug }}.jsonl --verbose
          
      - name: Note error for later
        if: ${{ failure() }}
        run: |
          mkdir error_counts
          touch error_counts/${{ matrix.slug }}.txt
      
      - name: Notify about failure
        if: ${{ failure()  && matrix.error_count > 0 && inputs.send-notifications }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          title: "🔴 Website-Check für «${{ matrix.label }}» fehlgeschlagen"
          summary: GitHub Action fehlgeschlagen für «${{ matrix.label }}»
          theme_color: CC0000
          actions: '[{ "@type": "OpenUri", "name": "Logs anschauen", "targets": [{ "os": "default", "uri": "https://github.com/ebp-group/website-keyword-monitor/actions/runs/${{ github.run_id }}?check_suite_focus=true" }] }]'
            
      - name: Upload hash as artifact
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: output-${{ matrix.slug }}
          path: |
            new_hashes
            matches
            error_counts

  update_error_count:
    needs: crawl
    if: always()
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get install sqlite3
      - name: Populate database
        env:
           CSV_PATH: ${{ inputs.csv-path }}
        run: ./workflow/populate_database.sh $CSV_PATH

      - name: Download output
        uses: actions/download-artifact@v4
        with:
          pattern: output-*
          path: output
          merge-multiple: true

      - name: Update error counts
        run: ./workflow/update_from_artifacts.sh

      - name: Export database
        env:
           CSV_PATH: ${{ inputs.csv-path }}
        run: ./workflow/export_database_to_csv.sh $CSV_PATH

      - name: Check if there are changes in the repo
        run: |
            git status --porcelain
            if [[ -z $(git status --porcelain) ]];
            then
              echo "Repo is clean"
              echo "changed=0" >> $GITHUB_OUTPUT
            else
              echo "Repo is dirty"
              echo "changed=1" >> $GITHUB_OUTPUT
            fi
        id: changes

      - name: Commit and push to repo
        if: ${{ steps.changes.outputs.changed == 1 && inputs.commit-error-count }}
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: ${{ github.ref_name }}
          name: GitHub Action Bot
          email: website-keyword-monitor@users.noreply.github.com
          commit-message: Update counts
          rebase: 'true'

      - name: Notify about failure
        if: ${{ failure() && inputs.send-notifications }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          title: "🔴 GitHub Commit fehlgeschlagen."
          summary: GitHub Action fehlgeschlagen.
          theme_color: CC0000
          actions: '[{ "@type": "OpenUri", "name": "Logs anschauen", "targets": [{ "os": "default", "uri": "https://github.com/ebp-group/website-keyword-monitor/actions/runs/${{ github.run_id }}?check_suite_focus=true" }] }]'
