name: Manual check of websites

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
      notifications:
          description: 'True to send notifications'
          required: true
          default: false
          type: boolean
      commit:
          description: 'True to commit hashes'
          required: true
          default: false
          type: boolean

jobs:
  check_aubonne_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      title: Aubonne
      environment: ${{ inputs.environment }}
      csv-path: csv/aubonne.csv
      keywords-path: keywords/aubonne.txt
      send-notifications: ${{ inputs.notifications }}
      commit-error-count: ${{ inputs.commit }}
    secrets: inherit
      
  check_dietlikon_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      title: Dietlikon
      environment: ${{ inputs.environment }}
      csv-path: csv/dietlikon.csv
      keywords-path: keywords/dietlikon.txt
      send-notifications: ${{ inputs.notifications }}
      commit-error-count: ${{ inputs.commit }}
    secrets: inherit
      
  check_grancia_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      title: Grancia
      environment: ${{ inputs.environment }}
      csv-path: csv/grancia.csv
      keywords-path: keywords/grancia.txt
      send-notifications: ${{ inputs.notifications }}
      commit-error-count: ${{ inputs.commit }}
    secrets: inherit
      
  check_itingen_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      title: Itingen
      environment: ${{ inputs.environment }}
      csv-path: csv/itingen.csv
      keywords-path: keywords/itingen.txt
      send-notifications: ${{ inputs.notifications }}
      commit-error-count: ${{ inputs.commit }}
    secrets: inherit
      
  check_lyssach_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      title: Lyssach
      environment: ${{ inputs.environment }}
      csv-path: csv/lyssach.csv
      keywords-path: keywords/lyssach.txt
      send-notifications: ${{ inputs.notifications }}
      commit-error-count: ${{ inputs.commit }}
    secrets: inherit

  check_pratteln_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      title: Pratteln
      environment: ${{ inputs.environment }}
      csv-path: csv/pratteln.csv
      keywords-path: keywords/pratteln.txt
      send-notifications: ${{ inputs.notifications }}
      commit-error-count: ${{ inputs.commit }}
    secrets: inherit

  check_riddes_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      title: Riddes/Saxon
      environment: ${{ inputs.environment }}
      csv-path: csv/riddes.csv
      keywords-path: keywords/riddes.txt
      send-notifications: ${{ inputs.notifications }}
      commit-error-count: ${{ inputs.commit }}
    secrets: inherit

  check_rothenburg_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      title: Rothenburg
      environment: ${{ inputs.environment }}
      csv-path: csv/rothenburg.csv
      keywords-path: keywords/rothenburg.txt
      send-notifications: ${{ inputs.notifications }}
      commit-error-count: ${{ inputs.commit }}
    secrets: inherit

  check_spreitenbach_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      title: Spreitenbach
      environment: ${{ inputs.environment }}
      csv-path: csv/spreitenbach.csv
      keywords-path: keywords/spreitenbach.txt
      send-notifications: ${{ inputs.notifications }}
      commit-error-count: ${{ inputs.commit }}
    secrets: inherit

  check_st_gallen_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      title: St. Gallen
      environment: ${{ inputs.environment }}
      csv-path: csv/st_gallen.csv
      keywords-path: keywords/st_gallen.txt
      send-notifications: ${{ inputs.notifications }}
      commit-error-count: ${{ inputs.commit }}
    secrets: inherit

  check_vernier_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      title: Vernier
      environment: ${{ inputs.environment }}
      csv-path: csv/vernier.csv
      keywords-path: keywords/vernier.txt
      send-notifications: ${{ inputs.notifications }}
      commit-error-count: ${{ inputs.commit }}
    secrets: inherit

  notify:
    needs:
      - check_aubonne_websites
      - check_dietlikon_websites
      - check_grancia_websites
      - check_itingen_websites
      - check_lyssach_websites
      - check_pratteln_websites
      - check_riddes_websites
      - check_rothenburg_websites
      - check_spreitenbach_websites
      - check_st_gallen_websites
      - check_vernier_websites
    if: ${{ always() }}
    uses: ebp-group/website-keyword-monitor/.github/workflows/notifications.yml@main
    with:
      environment: ${{ inputs.environment }}
      send-notifications: ${{ inputs.notifications }}
    secrets: inherit

  update_hashes:
    needs: notify
    if: ${{ needs.notify.result == 'success' }}
    uses: ebp-group/website-keyword-monitor/.github/workflows/update_hashes.yml@main
    with:
      environment: ${{ inputs.environment }}
      send-notifications: ${{ inputs.notifications }}
      commit-hashes: ${{ inputs.commit }}
    secrets: inherit
