name: Notification about new matches

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Check all websites]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download latest artifact
        run: python lib/download_data_from_github.py --name output
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_BRANCH: ${{ github.ref_name }}
          GITHUB_REPO_OWNER: ebp-group
          GITHUB_REPO: website-keyword-monitor

      - name: Send notification
        run: |
          cat matches/*.jsonl > all_matches.jsonl
          python ./lib/notifications.py --matches all_matches.jsonl --run-url "https://github.com/ebp-group/website-keyword-monitor/actions/runs/${{ github.run_id }}?check_suite_focus=true" --verbose
          
      - name: Notify about failure
        if: ${{ failure() }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          title: "🔴 Notifikation fehlgeschlagen"
          summary: GitHub Action fehlgeschlagen
          theme_color: CC0000
          actions: '[{ "@type": "OpenUri", "name": "Logs anschauen", "targets": [{ "os": "default", "uri": "https://github.com/ebp-group/website-keyword-monitor/actions/runs/${{ github.run_id }}?check_suite_focus=true" }] }]'
