name: Send notifications to MS Teams

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to run this job on'
        required: true
        type: string
      send-notifications:
        description: 'Run this workflow with notifications'
        default: true
        required: false
        type: boolean
    secrets:
      MS_TEAMS_WEBHOOK_URL:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    if: ${{ inputs.send-notifications }}

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download output
        uses: actions/download-artifact@v3
        with:
          name: output
          path: output
          
      - name: Send notification
        env:
           MS_TEAMS_WEBHOOK_URL:  ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
        run: |
          cat output/matches/*.jsonl > all_matches.jsonl
          python ./lib/notifications.py --matches all_matches.jsonl --run-url "https://github.com/ebp-group/website-keyword-monitor/actions/runs/${{ github.run_id }}?check_suite_focus=true" --verbose
          
      - name: Notify about failure
        if: ${{ failure()  && inputs.send-notifications }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          title: "🔴 Notifikation fehlgeschlagen"
          summary: GitHub Action fehlgeschlagen
          theme_color: CC0000
          actions: '[{ "@type": "OpenUri", "name": "Logs anschauen", "targets": [{ "os": "default", "uri": "https://github.com/ebp-group/website-keyword-monitor/actions/runs/${{ github.run_id }}?check_suite_focus=true" }] }]'
